site_name: Gabriel Gerner Maggion | ANN-DL
site_author: Gabriel Gerner Maggion
site_url: https://gabrielgmaggion-dot.github.io/ann-dl/
repo_url: https://github.com/gabrielgmaggion-dot/ann-dl
repo_name: gabrielgmaggion-dot/ann-dl

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Início: index.md
  - Exercícios:
      - 1. Dados: exercises/data/index.md
